/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import javax.swing.JLabel;

/**
 *
 * @author JULIO CESAR BERNAL
 */
public class IngresarEgresos extends javax.swing.JFrame {

    private ControlAddEgres controler;
    private Modelo modelo;

    public IngresarEgresos(Modelo m) {
        modelo = m;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numero_10 = new javax.swing.JButton();
        especificidad_ingreso = new javax.swing.JComboBox<>();
        notas = new javax.swing.JTextField();
        cuentas = new javax.swing.JComboBox<>();
        cantidad = new javax.swing.JTextField();
        numero_2 = new javax.swing.JButton();
        numero_1 = new javax.swing.JButton();
        numero_3 = new javax.swing.JButton();
        numero_4 = new javax.swing.JButton();
        numero_5 = new javax.swing.JButton();
        numero_6 = new javax.swing.JButton();
        numero_7 = new javax.swing.JButton();
        numero_8 = new javax.swing.JButton();
        numero_9 = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        n0 = new javax.swing.JButton();
        categoriaGastos = new javax.swing.JComboBox<>();
        cuenta = new javax.swing.JComboBox<>();
        cantidad1 = new javax.swing.JTextField();
        n2 = new javax.swing.JButton();
        n1 = new javax.swing.JButton();
        n3 = new javax.swing.JButton();
        n4 = new javax.swing.JButton();
        n5 = new javax.swing.JButton();
        n6 = new javax.swing.JButton();
        n7 = new javax.swing.JButton();
        n8 = new javax.swing.JButton();
        n9 = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        aceptar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        nota = new javax.swing.JTextArea();

        numero_10.setText("0");

        especificidad_ingreso.setEditable(true);
        especificidad_ingreso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ahorros personales", "Arrendamientos y cánones", "Salario", "Trabajo a tiempo parcial" }));

        notas.setText("Notas");
        notas.setDragEnabled(true);

        cuentas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        numero_2.setText("2");

        numero_1.setText("1");

        numero_3.setText("3");

        numero_4.setText("4");

        numero_5.setText("5");

        numero_6.setText("6");

        numero_7.setText("7");

        numero_8.setText("8");

        numero_9.setText("9");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 0, 0));
        titulo.setText("ADICIONAR GASTOS");

        n0.setText("0");

        categoriaGastos.setEditable(true);
        categoriaGastos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alimentos y Bebidas", "Parquimetro", "Automóvil", "Comestibles", "Compras", "Entretenimiento", "Familia", "Gasolina ", "Médico", "Otro", "Regalos y Donaciones", "Salud y Bienestar", "Utilidades", "Viviendas" }));

        cuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        n2.setText("2");

        n1.setText("1");

        n3.setText("3");

        n4.setText("4");

        n5.setText("5");

        n6.setText("6");

        n7.setText("7");

        n8.setText("8");

        n9.setText("9");

        cancelar.setText("Cancelar");

        aceptar.setText("Aceptar");

        nota.setColumns(20);
        nota.setRows(5);
        jScrollPane1.setViewportView(nota);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(aceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cuenta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(n0)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(n7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(n8))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(n4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(n5))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(n1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(n2)))
                                    .addGap(27, 27, 27)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(n3)
                                        .addComponent(n6)
                                        .addComponent(n9))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                            .addComponent(categoriaGastos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(4, 4, 4)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 289, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(aceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(99, 99, 99)
                    .addComponent(cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(categoriaGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(n1)
                        .addComponent(n2)
                        .addComponent(n3))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(n4)
                        .addComponent(n5)
                        .addComponent(n6))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(n7)
                        .addComponent(n8)
                        .addComponent(n9))
                    .addGap(18, 18, 18)
                    .addComponent(n0)
                    .addContainerGap(138, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField cantidad;
    private javax.swing.JTextField cantidad1;
    private javax.swing.JComboBox<String> categoriaGastos;
    private javax.swing.JComboBox<String> cuenta;
    private javax.swing.JComboBox<String> cuentas;
    private javax.swing.JComboBox<String> especificidad_ingreso;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton n0;
    private javax.swing.JButton n1;
    private javax.swing.JButton n2;
    private javax.swing.JButton n3;
    private javax.swing.JButton n4;
    private javax.swing.JButton n5;
    private javax.swing.JButton n6;
    private javax.swing.JButton n7;
    private javax.swing.JButton n8;
    private javax.swing.JButton n9;
    private javax.swing.JTextArea nota;
    private javax.swing.JTextField notas;
    private javax.swing.JButton numero_1;
    private javax.swing.JButton numero_10;
    private javax.swing.JButton numero_2;
    private javax.swing.JButton numero_3;
    private javax.swing.JButton numero_4;
    private javax.swing.JButton numero_5;
    private javax.swing.JButton numero_6;
    private javax.swing.JButton numero_7;
    private javax.swing.JButton numero_8;
    private javax.swing.JButton numero_9;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables

    Modelo getModelo() {
        return modelo;
    }

    public JLabel getTitulo() {
        return titulo;
    }
    
    

}
