/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import javax.swing.JButton;

/**
 *
 * @author Estudiantes
 */
public class VistaInformes extends javax.swing.JFrame {

    private ControladorInformes cntrlReg;
    private Modelo modelo;

    public VistaInformes(Modelo m) {
        modelo = m;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lResgistros = new javax.swing.JLabel();
        btmGasto = new javax.swing.JButton();
        btmIngreso = new javax.swing.JButton();
        btmContra = new javax.swing.JButton();
        btmRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registros");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lResgistros.setFont(new java.awt.Font("Perpetua Titling MT", 0, 24)); // NOI18N
        lResgistros.setText("informes");
        lResgistros.setToolTipText("");

        btmGasto.setFont(new java.awt.Font("Miriam", 0, 18)); // NOI18N
        btmGasto.setText("informe de gastos");

        btmIngreso.setFont(new java.awt.Font("Miriam", 0, 18)); // NOI18N
        btmIngreso.setText("informe de ingresos");

        btmContra.setFont(new java.awt.Font("Miriam", 0, 18)); // NOI18N
        btmContra.setText("ingresos contra gastos");

        btmRegresar.setFont(new java.awt.Font("Miriam", 0, 18)); // NOI18N
        btmRegresar.setText("regresar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lResgistros, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btmGasto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btmContra, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                        .addComponent(btmIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btmRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lResgistros, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btmIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btmGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btmContra, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btmRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmContra;
    private javax.swing.JButton btmGasto;
    private javax.swing.JButton btmIngreso;
    private javax.swing.JButton btmRegresar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lResgistros;
    // End of variables declaration//GEN-END:variables

    public ControladorInformes getControlRegistro() {
        if (cntrlReg == null) {
            cntrlReg = new ControladorInformes(this);
        }
        return cntrlReg;
    }

    //modelo
    private void capturarEventos() {
        btmIngreso.addActionListener(cntrlReg);
        btmGasto.addActionListener(cntrlReg);
        btmContra.addActionListener(cntrlReg);
        btmRegresar.addActionListener(cntrlReg);
    }

    public JButton getBtmContra() {
        return btmContra;
    }

    public JButton getBtmGasto() {
        return btmGasto;
    }

    public JButton getBtmIngreso() {
        return btmIngreso;
    }

    public JButton getBtmRegresar() {
        return btmRegresar;
    }

}
