/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Estudiantes
 */
public class VistaHistorial extends javax.swing.JFrame {

    /**
     * Creates new form Historial
     */
    
    private Modelo modelo;
    private ControladorHistorial contoler;
    public VistaHistorial(Modelo m) {
        modelo = m;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHistorial1 = new javax.swing.JPanel();
        lhistorial = new javax.swing.JLabel();
        panelHistorial2 = new javax.swing.JPanel();
        lHistorial = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Historial");

        lhistorial.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        lhistorial.setText("historial");

        javax.swing.GroupLayout panelHistorial1Layout = new javax.swing.GroupLayout(panelHistorial1);
        panelHistorial1.setLayout(panelHistorial1Layout);
        panelHistorial1Layout.setHorizontalGroup(
            panelHistorial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHistorial1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lhistorial)
                .addContainerGap(298, Short.MAX_VALUE))
        );
        panelHistorial1Layout.setVerticalGroup(
            panelHistorial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHistorial1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(lhistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lHistorial.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelHistorial2Layout = new javax.swing.GroupLayout(panelHistorial2);
        panelHistorial2.setLayout(panelHistorial2Layout);
        panelHistorial2Layout.setHorizontalGroup(
            panelHistorial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelHistorial2Layout.setVerticalGroup(
            panelHistorial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHistorial2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHistorial1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelHistorial2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelHistorial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelHistorial2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public JPanel getPanelHistorial2() {
        return panelHistorial2;
    }

    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lHistorial;
    private javax.swing.JLabel lhistorial;
    private javax.swing.JPanel panelHistorial1;
    private javax.swing.JPanel panelHistorial2;
    // End of variables declaration//GEN-END:variables
}
